/*
 * EWS Road Distance
 *
 * With the EWS Road Distance service you can query pre-calculated distances and additional information for relations between reference locations in Europe.
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.ews.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.ews.Model
{
    /// <summary>
    /// A location suggested for the input.
    /// </summary>
    [DataContract(Name = "SuggestedLocation")]
    public partial class SuggestedLocation : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public LocationType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestedLocation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SuggestedLocation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestedLocation" /> class.
        /// </summary>
        /// <param name="country">The country represented by its code according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). (required).</param>
        /// <param name="postalCode">The postal code, or zip-code, which is used by a postal authority of a country..</param>
        /// <param name="locality">The name of the city or district in the language spoken in that country or region, always transliterated to Latin. (required).</param>
        /// <param name="type">type (required).</param>
        public SuggestedLocation(string country = default(string), string postalCode = default(string), string locality = default(string), LocationType type = default(LocationType))
        {
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for SuggestedLocation and cannot be null");
            }
            this.Country = country;
            // to ensure "locality" is required (not null)
            if (locality == null)
            {
                throw new ArgumentNullException("locality is a required property for SuggestedLocation and cannot be null");
            }
            this.Locality = locality;
            this.Type = type;
            this.PostalCode = postalCode;
        }

        /// <summary>
        /// The country represented by its code according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
        /// </summary>
        /// <value>The country represented by its code according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).</value>
        /// <example>DE</example>
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// The postal code, or zip-code, which is used by a postal authority of a country.
        /// </summary>
        /// <value>The postal code, or zip-code, which is used by a postal authority of a country.</value>
        /// <example>76131</example>
        [DataMember(Name = "postalCode", EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// The name of the city or district in the language spoken in that country or region, always transliterated to Latin.
        /// </summary>
        /// <value>The name of the city or district in the language spoken in that country or region, always transliterated to Latin.</value>
        /// <example>Karlsruhe</example>
        [DataMember(Name = "locality", IsRequired = true, EmitDefaultValue = true)]
        public string Locality { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuggestedLocation {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Locality: ").Append(Locality).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
