/* tslint:disable */
/* eslint-disable */
/**
 * EWS Road Distance
 * With the EWS Road Distance service you can query pre-calculated distances and additional information for relations between reference locations in Europe.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationType } from './LocationType';
import {
    LocationTypeFromJSON,
    LocationTypeFromJSONTyped,
    LocationTypeToJSON,
} from './LocationType';

/**
 * The complete location used for start or destination of the relation.
 * @export
 * @interface ResponseLocation
 */
export interface ResponseLocation {
    /**
     * The country represented by its code according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
     * @type {string}
     * @memberof ResponseLocation
     */
    country: string;
    /**
     * The postal code, or zip-code, which is used by a postal authority of a country.
     * @type {string}
     * @memberof ResponseLocation
     */
    postalCode?: string;
    /**
     * The name of the city or district in the language spoken in that country or region, always transliterated to Latin.
     * @type {string}
     * @memberof ResponseLocation
     */
    locality: string;
    /**
     * The latitude in degrees (WGS84/EPSG:4326) from south to north, if requested.
     * @type {number}
     * @memberof ResponseLocation
     */
    latitude?: number;
    /**
     * The longitude in degrees (WGS84/EPSG:4326) from west to east, if requested.
     * @type {number}
     * @memberof ResponseLocation
     */
    longitude?: number;
    /**
     * 
     * @type {LocationType}
     * @memberof ResponseLocation
     */
    type: LocationType;
}

/**
 * Check if a given object implements the ResponseLocation interface.
 */
export function instanceOfResponseLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "locality" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ResponseLocationFromJSON(json: any): ResponseLocation {
    return ResponseLocationFromJSONTyped(json, false);
}

export function ResponseLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': json['country'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'locality': json['locality'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'type': LocationTypeFromJSON(json['type']),
    };
}

export function ResponseLocationToJSON(value?: ResponseLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'postalCode': value.postalCode,
        'locality': value.locality,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'type': LocationTypeToJSON(value.type),
    };
}

