/* tslint:disable */
/* eslint-disable */
/**
 * EWS Road Distance
 * With the EWS Road Distance service you can query pre-calculated distances and additional information for relations between reference locations in Europe.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResultsType = {
    COORDINATES: 'COORDINATES',
    TOLL_DISTANCE: 'TOLL_DISTANCE'
} as const;
export type ResultsType = typeof ResultsType[keyof typeof ResultsType];


export function instanceOfResultsType(value: any): boolean {
    for (const key in ResultsType) {
        if (Object.prototype.hasOwnProperty.call(ResultsType, key)) {
            if (ResultsType[key as keyof typeof ResultsType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResultsTypeFromJSON(json: any): ResultsType {
    return ResultsTypeFromJSONTyped(json, false);
}

export function ResultsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultsType {
    return json as ResultsType;
}

export function ResultsTypeToJSON(value?: ResultsType | null): any {
    return value as any;
}

