/* tslint:disable */
/* eslint-disable */
/**
 * EWS Road Distance
 * With the EWS Road Distance service you can query pre-calculated distances and additional information for relations between reference locations in Europe.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationType } from './LocationType';
import {
    LocationTypeFromJSON,
    LocationTypeFromJSONTyped,
    LocationTypeToJSON,
} from './LocationType';

/**
 * A location suggested for the input.
 * @export
 * @interface SuggestedLocation
 */
export interface SuggestedLocation {
    /**
     * The country represented by its code according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
     * @type {string}
     * @memberof SuggestedLocation
     */
    country: string;
    /**
     * The postal code, or zip-code, which is used by a postal authority of a country.
     * @type {string}
     * @memberof SuggestedLocation
     */
    postalCode?: string;
    /**
     * The name of the city or district in the language spoken in that country or region, always transliterated to Latin.
     * @type {string}
     * @memberof SuggestedLocation
     */
    locality: string;
    /**
     * 
     * @type {LocationType}
     * @memberof SuggestedLocation
     */
    type: LocationType;
}

/**
 * Check if a given object implements the SuggestedLocation interface.
 */
export function instanceOfSuggestedLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "locality" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function SuggestedLocationFromJSON(json: any): SuggestedLocation {
    return SuggestedLocationFromJSONTyped(json, false);
}

export function SuggestedLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestedLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': json['country'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'locality': json['locality'],
        'type': LocationTypeFromJSON(json['type']),
    };
}

export function SuggestedLocationToJSON(value?: SuggestedLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'postalCode': value.postalCode,
        'locality': value.locality,
        'type': LocationTypeToJSON(value.type),
    };
}

