/*
 * EWS Road Distance
 * With the EWS Road Distance service you can query pre-calculated distances and additional information for relations between reference locations in Europe.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.ews.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.ews.model.ResponseLocation;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.ews.ApiClient;
/**
 * RoadDistanceResponse
 */
@JsonPropertyOrder({
  RoadDistanceResponse.JSON_PROPERTY_DISTANCE,
  RoadDistanceResponse.JSON_PROPERTY_TOLL_DISTANCE,
  RoadDistanceResponse.JSON_PROPERTY_START,
  RoadDistanceResponse.JSON_PROPERTY_DESTINATION,
  RoadDistanceResponse.JSON_PROPERTY_DATA_VERSION,
  RoadDistanceResponse.JSON_PROPERTY_REGION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T06:50:19.107527760Z[Etc/UTC]", comments = "Generator version: 7.7.0")
public class RoadDistanceResponse {
  public static final String JSON_PROPERTY_DISTANCE = "distance";
  private Integer distance;

  public static final String JSON_PROPERTY_TOLL_DISTANCE = "tollDistance";
  private Integer tollDistance;

  public static final String JSON_PROPERTY_START = "start";
  private ResponseLocation start;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  private ResponseLocation destination;

  public static final String JSON_PROPERTY_DATA_VERSION = "dataVersion";
  private String dataVersion;

  public static final String JSON_PROPERTY_REGION = "region";
  private String region;

  public RoadDistanceResponse() { 
  }

  public RoadDistanceResponse distance(Integer distance) {
    this.distance = distance;
    return this;
  }

  /**
   * The distance of the relation [m].
   * minimum: 0
   * @return distance
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDistance() {
    return distance;
  }


  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDistance(Integer distance) {
    this.distance = distance;
  }


  public RoadDistanceResponse tollDistance(Integer tollDistance) {
    this.tollDistance = tollDistance;
    return this;
  }

  /**
   * The distance of toll roads of the relation [m], if requested.
   * minimum: 0
   * @return tollDistance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOLL_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTollDistance() {
    return tollDistance;
  }


  @JsonProperty(JSON_PROPERTY_TOLL_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTollDistance(Integer tollDistance) {
    this.tollDistance = tollDistance;
  }


  public RoadDistanceResponse start(ResponseLocation start) {
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ResponseLocation getStart() {
    return start;
  }


  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStart(ResponseLocation start) {
    this.start = start;
  }


  public RoadDistanceResponse destination(ResponseLocation destination) {
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ResponseLocation getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(ResponseLocation destination) {
    this.destination = destination;
  }


  public RoadDistanceResponse dataVersion(String dataVersion) {
    this.dataVersion = dataVersion;
    return this;
  }

  /**
   * The version of the data by year.
   * @return dataVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDataVersion() {
    return dataVersion;
  }


  @JsonProperty(JSON_PROPERTY_DATA_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataVersion(String dataVersion) {
    this.dataVersion = dataVersion;
  }


  public RoadDistanceResponse region(String region) {
    this.region = region;
    return this;
  }

  /**
   * The region which was searched for the reference locations.
   * @return region
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRegion() {
    return region;
  }


  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegion(String region) {
    this.region = region;
  }


  /**
   * Return true if this RoadDistanceResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoadDistanceResponse roadDistanceResponse = (RoadDistanceResponse) o;
    return Objects.equals(this.distance, roadDistanceResponse.distance) &&
        Objects.equals(this.tollDistance, roadDistanceResponse.tollDistance) &&
        Objects.equals(this.start, roadDistanceResponse.start) &&
        Objects.equals(this.destination, roadDistanceResponse.destination) &&
        Objects.equals(this.dataVersion, roadDistanceResponse.dataVersion) &&
        Objects.equals(this.region, roadDistanceResponse.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distance, tollDistance, start, destination, dataVersion, region);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoadDistanceResponse {\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    tollDistance: ").append(toIndentedString(tollDistance)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    dataVersion: ").append(toIndentedString(dataVersion)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `distance` to the URL query string
    if (getDistance() != null) {
      joiner.add(String.format("%sdistance%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDistance()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `tollDistance` to the URL query string
    if (getTollDistance() != null) {
      joiner.add(String.format("%stollDistance%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTollDistance()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `start` to the URL query string
    if (getStart() != null) {
      joiner.add(getStart().toUrlQueryString(prefix + "start" + suffix));
    }

    // add `destination` to the URL query string
    if (getDestination() != null) {
      joiner.add(getDestination().toUrlQueryString(prefix + "destination" + suffix));
    }

    // add `dataVersion` to the URL query string
    if (getDataVersion() != null) {
      joiner.add(String.format("%sdataVersion%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDataVersion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `region` to the URL query string
    if (getRegion() != null) {
      joiner.add(String.format("%sregion%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRegion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

